ncp:
  api:
    client-id: re2p8027kc
    client-secret: QZ0gf3e6IqurEFZ6oaqmnBeJ1Wrpz53Bi0h0E4KM

    api-access: bayBaYR8dcwmMeO2XLqE
    api-secret: ilCwHf4BYfA2yr0u0LgpqpZMaNF5oH5tdXwBmNcS

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp